### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by rubensamarojr** [rubensamarojr/polymps#7]
- [ ] Velocity Laplacian in the explicit part. Need particle-polygon search 2x.
- [ ] NPCD using look table like pnd
- [ ] BC wall pressure
- [ ] Print TXT file of the screen and output simulation info 
- [ ] Json input jump over irrelevant data for the case
- [ ] Update branchs
- [ ] Mean pressure in corners. Perform a test.
- [ ] Find Libs that give all triangles near the particle, or at least the average of normals and distances.
- [ ] Typedef double real
- [ ] Typedef float real
